import { Volkhov } from "next/font/google";
import "./globals.css";

const volkhov = Volkhov({
  subsets: ['latin'],
  weight: ['400', '700'],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={volkhov.className}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
